### ISSUE TITLE
Manage the status of the motion sensor

### ISSUE THREAD

**Issue by DivanX10** [rodpayne/home-assistant#3]
Hi. I have a motion sensor from xiaomi and a gateway xiaomi 2, the firmware is original. My motion sensors are switched to service mode and they record movement every 5 seconds. I did as you wrote on the forum. The status of the motion sensor is reset after any period of time, even after 5 seconds. But if you walk in front of the motion sensor again, the detected status is not displayed, you need to wait 2 minutes and then it will show the detected status and after 5 seconds (I specified this time) it will reset the detected status to not detected. You can somehow get the home assistant to respond accurately to movement? There is a movement status detected after 5 seconds of no movement - status is not found, then create movement and status must be detected.

I have installed **Home Assistant 2020.12.1**

Read it here https://community.home-assistant.io/t/how-to-manually-set-state-value-of-sensor/43975/2

1) **In configuration.yaml added python_script:**
![config](https://user-images.githubusercontent.com/64090632/103046011-b8ef4980-4597-11eb-8434-0bed25bdb882.jpg)

2) **Created the python_scripts folder**
![python_scripts01](https://user-images.githubusercontent.com/64090632/103046041-d0c6cd80-4597-11eb-86a9-74504e1a4c18.JPG)

3) **Created a file set_state.py**
![set_state](https://user-images.githubusercontent.com/64090632/103046057-dae8cc00-4597-11eb-94ed-ee019c4d50d4.JPG)

4) **I inserted your code into it**
5) **The service is available in the developer panel**
![service_yes](https://user-images.githubusercontent.com/64090632/103046094-0a97d400-4598-11eb-9b41-e7a99327abfe.jpg)

6) **Created automation**

alias: DD in the corridor deactivating the status
description: We check the operation of the creak to deactivate the motion sensor
trigger:
  - type: motion
    platform: device
    device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    entity_id: binary_sensor.motion_sensor_xxxxxxxxxxxxxxxx
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
condition: []
action:
  - data_template:
      entity_id: binary_sensor.motion_sensor_xxxxxxxxxxxxxxxxxxx
      state: 'off'
    service: python_script.set_state
mode: single

**Comment by rodpayne** [comment]
I have not used this sensor myself, but this seems to be the way that these sensors function.  They only detect again after two minutes, perhaps to conserve battery life.  Your "turn off" automation may need to wait for a period of time (greater that two minutes) before turning off the light.  Something like:
```
trigger:
    platform: state
    entity_id: 
      - binary_sensor.motion_sensor_xxxxxxxxxxxxxxxx
    to: 'off'
    for: 00:03:00  
```
See https://community.smartthings.com/t/making-xiaomi-motion-sensor-a-super-motion-sensor/139806.
See https://www.reddit.com/r/homeassistant/comments/bphsom/modifying_aqara_motion_sensors_to_track_every_5/.

**Comment by DivanX10** [comment]
I set up the motion sensor reset in this way and left a [detailed description](https://github.com/wernerhp/appdaemon_aqara_motion_sensors/issues/8) of how it is done so that others do not break their heads. Many authors of their projects do not know how to write instructions normally or do not write anything at all, and it is very difficult to understand what and how it is done.

Я настроил сброс датчика движения этим способом и оставил [подробное описание](https://github.com/wernerhp/appdaemon_aqara_motion_sensors/issues/8) как это делается, чтобы другие не ломали голову. Многие авторы своих проектов не умеют нормально писать инструкции или вовсе не пишут ничего и очень сложно понять, что и как это делается.

**Comment by rodpayne** [comment]
I do not use this particular hardware sensor or AppDaemon, so this issue is kind of out of my scope.  Thank you for taking the time to help other people.
